name: Lint PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: write

jobs:
  lint-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Validate PR Title
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            ci
            chore
            style
            refactor
            test
            revert
          requireScope: false
          subjectPattern: ^[A-Za-z].+$
          subjectPatternError: |
            The subject must start with an alphabetic character.
          wip: true
          validateSingleCommit: false
